import React from 'react';
import { marked } from 'marked';

interface AnalysisResultProps {
  markdown: string;
}

export const AnalysisResultView: React.FC<AnalysisResultProps> = ({ markdown }) => {
  // Use a simple synchronous parsing since we are using marked as a library
  const htmlContent = marked.parse(markdown) as string;

  const handleDownload = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'StackSentinel_Analysis.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto mt-8 animate-[slideUp_0.6s_ease-out_forwards] opacity-0">
      <div className="glass-panel rounded-xl overflow-hidden shadow-2xl shadow-black/50">
        
        {/* Header */}
        <div className="bg-cyber-darker/80 border-b border-slate-700/50 p-4 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <span className="material-symbols-rounded text-cyber-success">verified_user</span>
            <span className="text-slate-300 font-mono text-sm">ANALYSIS_COMPLETE</span>
          </div>
          <div className="flex items-center space-x-3">
            <button 
              onClick={handleDownload}
              className="flex items-center space-x-1 px-3 py-1 rounded bg-slate-800 border border-slate-700 hover:bg-slate-700 hover:border-cyber-primary/50 transition-colors text-xs text-slate-300 font-medium group"
              title="Download Report as Markdown"
            >
              <span className="material-symbols-rounded text-sm text-slate-400 group-hover:text-cyber-primary transition-colors">download</span>
              <span>Export</span>
            </button>
            <div className="flex items-center space-x-1 px-2 py-1 rounded bg-slate-800 border border-slate-700">
               <span className="w-2 h-2 rounded-full bg-cyber-success animate-pulse"></span>
               <span className="text-xs text-slate-400">Live</span>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="p-8 md:p-12 overflow-y-auto max-h-[800px]">
          <div 
            className="markdown-body font-sans text-slate-300"
            dangerouslySetInnerHTML={{ __html: htmlContent }}
          />
        </div>

        {/* Footer */}
        <div className="bg-cyber-darker/90 border-t border-slate-800 p-4 flex justify-between items-center text-xs text-slate-500 font-mono">
          <span>GENERATED BY GEMINI 3 PRO</span>
          <span>STACK_SENTINEL_V1.0</span>
        </div>
      </div>
      
      <style>{`
        @keyframes slideUp {
          from { transform: translateY(50px); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }
      `}</style>
    </div>
  );
};